export const TYPES = {
  GET_POSTS_REQUEST: "GET_POSTS_REQUEST",
  GET_POSTS_REQUEST_SUCCESS: "GET_POSTS_REQUEST_SUCCESS",
  GET_POSTS_REQUEST_ERROR: "GET_POSTS_REQUEST_SUCCESS",

  GET_POST_REQUEST: "GET_POST_REQUEST",
  GET_POST_REQUEST_SUCCESS: "GET_POST_SUCCESS",
  GET_POST_REQUEST_ERROR: "GET_POST_ERROR",

  NEW_POST_CARD_TOGGLE: "NEW_POST_CARD_TOGGLE",

  NEW_POST_REQUEST: "NEW_POST_REQUEST",
  NEW_POST_REQUEST_SUCCESS: "NEW_POST_REQUEST_SUCCESS",
  NEW_POST_REQUEST_ERROR: "NEW_POST_REQUEST_ERROR",

  NEW_MESSAGE_REQUEST: "NEW_MESSAGE_REQUEST",
  NEW_MESSAGE_REQUEST_SUCCESS: "NEW_MESSAGE_REQUEST_SUCCESS",
  NEW_MESSAGE_REQUEST_ERROR: "NEW_MESSAGE_REQUEST_ERROR",

  GET_MESSAGES_REQUEST: "GET_MESSAGES_REQUEST",
  GET_MESSAGES_REQUEST_SUCCESS: "GET_MESSAGES_REQUEST_SUCCESS",
  GET_MESSAGES_REQUEST_ERROR: "GET_MESSAGES_REQUEST_ERROR",
};
