export const TYPES = {
  GET_POSTS_REQUEST: "GET_POSTS_REQUEST",
  GET_POSTS_REQUEST_SUCCESS: "GET_POSTS_REQUEST_SUCCESS",
  GET_POSTS_REQUEST_ERROR: "GET_POSTS_REQUEST_SUCCESS",

  GET_POST_REQUEST: "GET_POST_REQUEST",
  GET_POST_SUCCESS: "GET_POST_SUCCESS",
  GET_POST_ERROR: "GET_POST_ERROR",

  NEW_POST_CARD_TOGGLE: "NEW_POST_CARD_TOGGLE",
};
